
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Content-Type = "text/javascript"

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"
